### ISSUE TITLE
No method in multimethod lt-restriction

### ISSUE THREAD

**Issue by postatum** [raml-org/datatype-expansion#35]
Getting canonical form of type `Cat` gives me following error. Error repeats when replacing `default` with `example`, `displayName`, `description` and maybe some other props - I didn't test them all.

```
#%RAML 1.0 Library

types:
  Animal:
    default: Animal
    type: string

  Cat:
    type: Animal
    default: MyCat
```

```
Error: No method in multimethod 'datatype-expansion.canonical-form/lt-restriction' for dispatch value: :default
    at Object.cljs$core$throw_no_method_error [as throw_no_method_error] (/home/post/projects/mulesoft/raml-parser-toolbelt/tools/datatype-expansion/examples/nodejs/node_modules/datatype-expansion/node/cljs/core.js:33311:8)
    at cljs.core.MultiFn.call.G__10851__4 (/home/post/projects/mulesoft/raml-parser-toolbelt/tools/datatype-expansion/examples/nodejs/node_modules/datatype-expansion/node/cljs/core.js:33382:11)
    at cljs.core.MultiFn.call.G__10851 [as call] (/home/post/projects/mulesoft/raml-parser-toolbelt/tools/datatype-expansion/examples/nodejs/node_modules/datatype-expansion/node/cljs/core.js:33630:20)
    at datatype_expansion$canonical_form$lt_restrictions (/home/post/projects/mulesoft/raml-parser-toolbelt/tools/datatype-expansion/examples/nodejs/node_modules/datatype-expansion/node/datatype_expansion/canonical_form.js:276:107)
    at /home/post/projects/mulesoft/raml-parser-toolbelt/tools/datatype-expansion/examples/nodejs/node_modules/datatype-expansion/node/datatype_expansion/canonical_form.js:489:120
    at cljs.core.MultiFn.call.G__10851__3 (/home/post/projects/mulesoft/raml-parser-toolbelt/tools/datatype-expansion/examples/nodejs/node_modules/datatype-expansion/node/cljs/core.js:33372:108)
    at cljs.core.MultiFn.call.G__10851 [as call] (/home/post/projects/mulesoft/raml-parser-toolbelt/tools/datatype-expansion/examples/nodejs/node_modules/datatype-expansion/node/cljs/core.js:33628:20)
    at /home/post/projects/mulesoft/raml-parser-toolbelt/tools/datatype-expansion/examples/nodejs/node_modules/datatype-expansion/node/datatype_expansion/canonical_form.js:747:107
    at cljs.core.MultiFn.call.G__10851__2 (/home/post/projects/mulesoft/raml-parser-toolbelt/tools/datatype-expansion/examples/nodejs/node_modules/datatype-expansion/node/cljs/core.js:33359:106)
    at cljs.core.MultiFn.call.G__10851 [as call] (/home/post/projects/mulesoft/raml-parser-toolbelt/tools/datatype-expansion/examples/nodejs/node_modules/datatype-expansion/node/cljs/core.js:33626:20)
```

**Comment by postatum** [comment]
@antoniogarrote please look into it ASAP, because this issue is blocking https://github.com/mulesoft/osprey/pull/116
