### ISSUE TITLE
Cycling expansion issue

### ISSUE THREAD

**Issue by jenschude** [raml-org/datatype-expansion#51]
Using the RAML below in Osprey with a cycling usage of a type I get following error message:

```
Error: No method in multimethod 'datatype-expansion.canonical-form/canonical-form' for dispatch value: fixpoint
    at Object.cljs$core$throw_no_method_error [as throw_no_method_error] (/workspace/osprey-raml1.0/node_modules/datatype-expansion/node/cljs/core.js:33311:8)
    at cljs.core.MultiFn.call.G__10851__2 (/workspace/osprey-raml1.0/node_modules/datatype-expansion/node/cljs/core.js:33356:11)
    at cljs.core.MultiFn.call.G__10851 [as call] (/workspace/osprey-raml1.0/node_modules/datatype-expansion/node/cljs/core.js:33626:20)
    at /workspace/osprey-raml1.0/node_modules/datatype-expansion/node/datatype_expansion/canonical_form.js:790:112
    at /workspace/osprey-raml1.0/node_modules/datatype-expansion/node/cljs/core.js:19036:96
    at /workspace/osprey-raml1.0/node_modules/datatype-expansion/node/cljs/core.js:19037:3
    at cljs.core.PersistentVector.cljs$core$IReduce$_reduce$arity$3 (/workspace/osprey-raml1.0/node_modules/datatype-expansion/node/cljs/core.js:19052:3)
    at Function.cljs.core.reduce.cljs$core$IFn$_invoke$arity$3 (/workspace/osprey-raml1.0/node_modules/datatype-expansion/node/cljs/core.js:7733:13)
    at cljs$core$reduce (/workspace/osprey-raml1.0/node_modules/datatype-expansion/node/cljs/core.js:7701:25)
    at /workspace/osprey-raml1.0/node_modules/datatype-expansion/node/datatype_expansion/canonical_form.js:788:166
```

```raml
#%RAML 1.0
title: Example API
types:
    Category:
        type: object
        properties:
            name:
                type: string
            children?:
                type: Category[]
/{id}:
  get:
    queryParameters:
      sort:
        enum: [username, name]
    responses:
      200:
        body:
          application/json:
            type: Category
```

**Comment by jenschude** [comment]
Also with an inheritance in between it's not working:

```
#%RAML 1.0
title: Example API
types:
    CategoryReference:
        type: object
        properties:
            id: string
            obj: Category
    Category:
        type: object
        properties:
            name:
                type: string
            children?:
                type: CategoryReference[]
/{id}:
  get:
    queryParameters:
      sort:
        enum: [username, name]
    responses:
      200:
        body:
          application/json:
            type: Category
