### ISSUE TITLE
Error incompatible types

### ISSUE THREAD

**Issue by jarrodek** [raml-org/datatype-expansion#70]
In new version I am receiving a lot of `incompatible types: [object, [object Object]]` errors when parsing the API: https://github.com/advanced-rest-client/raml-example-api

Stack:
```
Error: incompatible types: [object, [object Object]]
    at minType (/Users/pawelpsztyc/workspace/advanced-rest-client/raml2obj/node_modules/datatype-expansion/src/minType.js:302:9)
    at toCanonical (/Users/pawelpsztyc/workspace/advanced-rest-client/raml2obj/node_modules/datatype-expansion/src/canonical.js:162:36)
    at Object.canonicalForm (/Users/pawelpsztyc/workspace/advanced-rest-client/raml2obj/node_modules/datatype-expansion/src/canonical.js:19:12)
```

This is happening for the following types declared in the RAML:

-   AppPerson
-   Product
-   ExampleType.Org
-   ExampleType.AlertableAdmin

Previous version was expanding data types correctly.
I'm not sure what else I can add to help with debug.

**Comment by jarrodek** [comment]
I've also noticed that types that contains unions aren't expanded at all in this example.

This library is a dependency of the API console and ARC and the console is a dependency of the Exchange, API Kit and API designer so this potentially can affect a lot of Mulesoft's products.

**Comment by ForsakenHarmony** [comment]
How are you parsing it?

**Comment by jarrodek** [comment]
Like here: https://github.com/raml-org/datatype-expansion/issues/69

**Comment by jstoiko** [comment]
```sh
$ npm init
$ npm i --save raml-1-parser
$ npm i --save datatype-expansion@0.1.x
```
index.js:
```js
const raml = require('raml-1-parser');
const dtexp = require('datatype-expansion');

raml.loadApi('https://raw.githubusercontent.com/advanced-rest-client/raml-example-api/master/api.raml', {
    rejectOnErrors: false
})
.then(result => {
    return result.expand(true).toJSON({serializeMetadata: false});
})
.then(result => {
  const exp = dtexp.expandedForm(result.types[2].AppPerson, {'Resource': result.types[1].Resource, 'AppPerson': result.types[2].AppPerson})
  const can = dtexp.canonicalForm(exp)
  console.log(can)
});
```
then,
```sh
$ node index.js
```
works fine. but then,
```sh
$ npm i --save datatype-expansion@0.2.x
$ node index.js
```
throws:
```sh
(node:15955) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: incompatible types: [object, [object Object]]
```
