### ISSUE TITLE
Goog is not defined with Jest.

### ISSUE THREAD

**Issue by OverseePublic** [raml-org/datatype-expansion#72]
Hi, I recently updated mocha tests to jest tests, and the jest can run without any problem, but the issue I'm having is the `goog` object from another module.

With mocha, it's not a problem to access this `goog` object, but for some reason when I run it with jest, it is undefined.

I believe this has something to do with how jest runs, so any pointer or help would be appreciated.

P.S when I run the same test with mocha, this isn't issue.

Here's the stack trace.
>> ● Test suite failed to run
>>
>>     TypeError: goog.addDependency is not a function
>>
>>       at Object.<anonymous> (node_modules/raml2obj/node_modules/datatype-expansion/node/cljs_deps.js:1:95)
>>       at Object.<anonymous> (node_modules/raml2obj/node_modules/datatype-expansion/index.js:20:1)
>>       at Object.<anonymous> (node_modules/raml2obj/index.js:6:15)
>>       at Object.<anonymous> (node_modules/raml2html/index.js:3:18)

**Comment by ForsakenHarmony** [comment]
This seems to be a problem with the old version of `datatype-expansion`
